CREATE USER TrabalhoES IDENTIFIED BY TrabalhoES;
GRANT CONNECT,  RESOURCE, CREATE table, CREATE synonym, CREATE sequence TO TrabalhoES;

CREATE TABLE OBJETIVO 
(
  ID_OBJETIVO          number, 
  NM_DESCRICAO          varchar2(500)
);

ALTER TABLE OBJETIVO ADD CONSTRAINT PK_OBJETIVO PRIMARY KEY (ID_OBJETIVO);

CREATE TABLE USUARIO 
(
  ID_USUARIO          number,
  NM_NOME_USUARIO     varchar(200),
  ID_OBJETIVO          number
);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_OBJETIVO 
FOREIGN KEY (ID_OBJETIVO) REFERENCES OBJETIVO (ID_OBJETIVO);

   
CREATE SEQUENCE USUARIO_SEQ_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
